const  CartActionTypes = {
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
    ADD_ITEM: 'ADD_ITEM',
    CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
    INCRESE_ITEM_QUANTITY:'INCRESE_ITEM_QUANTITY',
    DECRESE_ITEM_QUANTITY:'DECRESE_ITEM_QUANTITY',
    CLEAR_CART:'CLEAR_CART'
    }
    
    export default CartActionTypes;